/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nuri
 */
public class Transaksi extends javax.swing.JFrame {
    private DefaultTableModel model;
    
    public void loadData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            Connection c = koneksi.koneksiDB();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM barang";
            ResultSet r = s.executeQuery(sql);
            
            while (r.next()) {                
                Object[] o = new Object[5];
                o [0] = r.getString("kode_barang");
                o [1] = r.getString("nama");
                o [2] = r.getString("kategori");
                o [3] = r.getString("jumlah");
                o [4] = r.getString("keadaan");
                
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (Exception e) {
            System.out.println("terjadi kesalahan");
        }}
    
public void cari() {
    DefaultTableModel tabel = new DefaultTableModel();

    tabel.addColumn("Kode Barang");
    tabel.addColumn("Nama Barang");
    tabel.addColumn("Kategori");
    tabel.addColumn("Jumlah");
    tabel.addColumn("Keadaan");

    try {
        Connection c = koneksi.koneksiDB();
        String sql = "Select * from barang where kode_barang like '%" + txCari.getText() + "%'" +
                "or nama like '%" + txCari.getText() + "%'";
        Statement stat = c.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        while (rs.next()) {
            tabel.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
            });
        }
        jTable1.setModel(tabel); // Setel model tabel ke model yang sudah difilter
    } catch (Exception e) {
        System.out.println("Cari Data Error");
    }
    
}
private void updateJumlahBarang() {
    try {
        Connection conn = koneksi.koneksiDB();
        PreparedStatement pst;

        // Dapatkan data barang berdasarkan nama barang
        String sqlSelect = "SELECT * FROM barang WHERE nama=?";
        pst = (PreparedStatement) conn.prepareStatement(sqlSelect);
        pst.setString(1, tfNamabarang.getText());
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // Ambil jumlah barang dari hasil query
            int jumlahBarang = rs.getInt("jumlah");

            // Hitung jumlah baru berdasarkan jenis transaksi
            int jumlahBaru;
            if ("PEMINJAMAN".equals(cbJenis.getSelectedItem())) {
                jumlahBaru = jumlahBarang - Integer.parseInt(tfJumlah.getText());
            } else if ("PEMUSNAHAN".equals(cbJenis.getSelectedItem())) {
                jumlahBaru = jumlahBarang - Integer.parseInt(tfJumlah.getText());
            } else {
                jumlahBaru = jumlahBarang + Integer.parseInt(tfJumlah.getText());
            }

            // Update jumlah barang di tabel barang
            String sqlUpdate = "UPDATE barang SET jumlah=? WHERE nama=?";
            pst = (PreparedStatement) conn.prepareStatement(sqlUpdate);
            pst.setInt(1, jumlahBaru);
            pst.setString(2, tfNamabarang.getText());
            pst.executeUpdate();
        }

    } catch (Exception e) {
        System.out.println("Terjadi kesalahan saat update jumlah barang: " + e.getMessage());
    }
}
    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        model = new DefaultTableModel();
        
        jTable1.setModel(model);
        
        model.addColumn("KODE BARANG");
        model.addColumn("NAMA BARANG");
        model.addColumn("KATEGORI");
        model.addColumn("JUMLAH");
        model.addColumn("KEADAAN");
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfTgl = new javax.swing.JTextField();
        tfIDTransaksi = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        tfJumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tfNamabarang = new javax.swing.JTextField();
        btnInput = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNamaPeminjam = new javax.swing.JTextField();
        txCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Transaksi Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 6, -1, -1));

        jLabel2.setText("ID Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, -1, -1));

        jLabel3.setText("Tanggal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, -1, -1));

        jLabel4.setText("Jenis Transaksi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 59, -1, -1));

        jLabel5.setText("Jumlah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 127, -1, -1));
        getContentPane().add(tfTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 96, 122, -1));

        tfIDTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(tfIDTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 56, 99, -1));

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEMINJAMAN", "PEMUSNAHAN", "PENGEMBALIAN" }));
        getContentPane().add(cbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 56, -1, -1));

        tfJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(tfJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 124, 121, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 285, 521, 275));

        jLabel6.setText("Nama Barang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 90, -1, -1));
        getContentPane().add(tfNamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 87, 121, -1));

        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 181, 485, -1));

        jLabel7.setText("Cari");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 248, -1, -1));

        jLabel8.setText("Nama Transaktor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 136, -1, -1));
        getContentPane().add(tfNamaPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 133, 122, -1));

        txCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCariActionPerformed(evt);
            }
        });
        getContentPane().add(txCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 245, 458, -1));

        jButton1.setText("Data Transaksi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 210, -1, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 210, -1, -1));

        jButton3.setText("MENU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 44));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgbirub.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDTransaksiActionPerformed

    private void tfJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahActionPerformed

    private void txCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCariActionPerformed
      cari();
    }//GEN-LAST:event_txCariActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int tabel = jTable1.getSelectedRow();
         tfNamabarang.setText(jTable1.getValueAt(tabel, 1).toString());
           tfJumlah.setText(jTable1.getValueAt(tabel, 3).toString());
            
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
       try{
         String sql = "INSERT INTO tb_transaksi VALUES('"         //membangun query sql memakai data yang dari input field
                 +tfIDTransaksi.getText()+"','"
                 +tfTgl.getText()+"','"
                 +tfNamaPeminjam.getText()+"','"
                 +cbJenis.getSelectedItem()+"','"
                 +tfNamabarang.getText()+"','"
                 +tfJumlah.getText()+"')";
                 
         java.sql.Connection conn= (java.sql.Connection)gui.koneksi.koneksiDB();
         java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                 pst.execute();
                 JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                 updateJumlahBarang();
     }//Menampilkan Pesan Error Ketika Data gagal disimpan
     catch (Exception e) {
         JOptionPane.showMessageDialog(null,"Data Gagal Di Simpan");
         System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_btnInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new DataTransaksi().show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tfIDTransaksi.setText(""); 
        tfTgl.setText("");
        tfNamaPeminjam.setText("");
        cbJenis.setSelectedItem("");
        tfNamabarang.setText("");
        tfJumlah.setText("");
        tfIDTransaksi.requestFocus();
        loadData();  // Mengosongkan semua input field dan fokus ke tfKdbarang
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new FUtamaAdmin().show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInput;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfIDTransaksi;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfNamaPeminjam;
    private javax.swing.JTextField tfNamabarang;
    private javax.swing.JTextField tfTgl;
    private javax.swing.JTextField txCari;
    // End of variables declaration//GEN-END:variables
}
